manifest:
  remotes:
    - name: ftc
      url-base: https://github.com/ftc          # <--- ADD REPO
  projects:
    - name: ftc
      remote: zmkfirmware
      revision: mouse-ftc                       # <--- ADD REVISION
      import: app/west.yml
  self:
    path: config
