manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/FilipParyz          # <--- ADD REPO
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: mouse-ftc                       # <--- ADD REVISION
      import: app/west.yml
  self:
    path: config
